version: '3'

services:
  rtkrcv:
    container_name: rtkrcv
    build: 
      context: rtkrcv
      dockerfile: Dockerfile
      args:
        - http_proxy
        - https_proxy

  logger:
    container_name: logger
    build:
      context: logger
      args:
        - http_proxy
        - https_proxy
