apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:

  restartPolicy: Never

  volumes:
  - name: logs
    emptyDir: {}

  containers:

  - name: "rtk-status-page-logger"
    image: "asia.gcr.io/crucial-citron-232505/rtk-status-page_logger:latest"
    volumeMounts:
    - name: logs
      mountPath: /logs
    env:
    - name: STATIONS
      value: ALIC7;BULA7
    - name: DBHOST
      valueFrom:
        secretKeyRef:
          name: rtk-status-page-secret
          key: DBHOST
    - name: DBPT
      value: "5432"
    - name: DBU
      value: "client"
    - name: DBPW
      valueFrom:
        secretKeyRef:
          name: rtk-status-page-secret
          key: DBPW
    - name: DBNAME
      value: "rtkstatuspage"

  - name: "rtk-status-page-rtkrcv"
    image: "asia.gcr.io/crucial-citron-232505/rtk-status-page_rtkrcv:latest"
    tty: true
    volumeMounts:
    - name: logs
      mountPath: /logs
    command: ["/bin/sh"]
    env:
    - name: STATIONS
      value: ALIC7;BULA7
    - name: AUSCORS
      valueFrom:
        secretKeyRef:
          name: rtk-status-page-secret
          key: AUSCORS
    args: ["-c", "sed -i 's/AUSCORS/'$(AUSCORS)'/' single.conf && export STATIONS=\"$(STATIONS)\" && for station in $$(echo ${STATIONS} | tr ';' ' '); do echo ${station} && cp single.conf ${station}.conf && sed -i 's/STATION/'${station}'/' ${station}.conf && screen -dm -S ${station} ./rtkrcv -s -o ${station}.conf; done && ./rtkrcv"]

