apiVersion: v1
kind: Pod
metadata:
  name: two-containers
spec:

  restartPolicy: Always

  volumes:
  - name: logs
    emptyDir: {}

  containers:

  - name: "rtk-status-page-logger"
    image: "asia.gcr.io/crucial-citron-232505/rtk-status-page_logger:latest"
    volumeMounts:
    - name: logs
      mountPath: /logs
    env:
    - name: STATIONS
      value: 01NA7;31NA0;ALBY7;ALIC7;ANDA7;ARMC4;ARUB7;BALA4;BBOO7;BDLE7;BEEC7;BMAN4;BNDY7;BRLA7;BRO14;BROC0;BULA7;BUR27;BURA4;CBLA7;WNTN7;MLAP7;RBYL7;CEDU7;CLYT7;COBG7;COCO7;COEN7;COOB7;COOL7;CRAN7;CUT07;DARW7;DODA7;DPRT4;EDSV4;ERMG4;ESPA4;EXMT4;FLND4;FROY7;GABO0;GGTN4;GROT7;HIL17;HNIS7;HOB27;HUGH4;HYDN4;JAB27;JERV4;JLCK4;JOG27;KALG4;KARR4;KAT17;KAT24;KELN4;KGIS4;KILK4;KUNU7;LAMB7;LARR7;LAUT4;LIAW0;LILY4;LKYA7;LONA4;LORD7;LURA4;MAC17;MAJU7;MCHL4;MEDO7;MNGO7;MOBS7;MRBA4;MRO14;MTCV7;MTDN4;MTEM0;MTIS4;MTMA4;MULG4;NAUR7;NCLF7;NEBO4;NHIL0;NMTN7;NORF7;NORS7;NTJN7;NULA7;OUS27;PARK4;PERT4;PNGM4;POHN4;PTGG7;PTHL7;PTLD0;PTSV7;RAVN4;RHPT7;RIVN4;RKLD7;RNIS7;RNSP7;RSBY4;SA457;SOLO4;SPBY0;STHG7;STNY0;STR17;STR24;STR30;SYDN7;SYM14;THEV7;TID17;TITG7;TMBO7;TOMP7;TOOW4;TOW27;TRN17;UCLA4;WAGN4;WARA0;WBEE7;WEND7;WILU7;WLAL7;WMGA7;XMIS4;YAR27;YAR37;YARR7;YEEL7;YELO4;YNKI0;YULA4;BDST4;TOOG4;BEE24;CBLT4;CLEV4;DALB4;GATT4;ROBI4;WARW4;WWLG0;TURO0;TBOB0;PTKL0;PRCE0;NSTA0;NBRK0;KIRR0;IHOE0;HERN0;GNGN0;GLB20;ECOR0;CNBN0;BKNL0;BING0;BARR0;ARD20
    - name: DBHOST
      valueFrom:
        secretKeyRef:
          name: rtk-status-page-secret
          key: DBHOST
    - name: DBPT
      value: "5432"
    - name: DBU
      value: "client"
    - name: DBPW
      valueFrom:
        secretKeyRef:
          name: rtk-status-page-secret
          key: DBPW
    - name: DBNAME
      value: "rtkstatuspage"

  - name: "rtk-status-page-rtkrcv"
    image: "asia.gcr.io/crucial-citron-232505/rtk-status-page_rtkrcv:latest"
    tty: true
    volumeMounts:
    - name: logs
      mountPath: /logs
    command: ["/bin/sh", "-c"]
    env:
    - name: STATIONS
      value: 01NA7;31NA0;ALBY7;ALIC7;ANDA7;ARMC4;ARUB7;BALA4;BBOO7;BDLE7;BEEC7;BMAN4;BNDY7;BRLA7;BRO14;BROC0;BULA7;BUR27;BURA4;CBLA7;WNTN7;MLAP7;RBYL7;CEDU7;CLYT7;COBG7;COCO7;COEN7;COOB7;COOL7;CRAN7;CUT07;DARW7;DODA7;DPRT4;EDSV4;ERMG4;ESPA4;EXMT4;FLND4;FROY7;GABO0;GGTN4;GROT7;HIL17;HNIS7;HOB27;HUGH4;HYDN4;JAB27;JERV4;JLCK4;JOG27;KALG4;KARR4;KAT17;KAT24;KELN4;KGIS4;KILK4;KUNU7;LAMB7;LARR7;LAUT4;LIAW0;LILY4;LKYA7;LONA4;LORD7;LURA4;MAC17;MAJU7;MCHL4;MEDO7;MNGO7;MOBS7;MRBA4;MRO14;MTCV7;MTDN4;MTEM0;MTIS4;MTMA4;MULG4;NAUR7;NCLF7;NEBO4;NHIL0;NMTN7;NORF7;NORS7;NTJN7;NULA7;OUS27;PARK4;PERT4;PNGM4;POHN4;PTGG7;PTHL7;PTLD0;PTSV7;RAVN4;RHPT7;RIVN4;RKLD7;RNIS7;RNSP7;RSBY4;SA457;SOLO4;SPBY0;STHG7;STNY0;STR17;STR24;STR30;SYDN7;SYM14;THEV7;TID17;TITG7;TMBO7;TOMP7;TOOW4;TOW27;TRN17;UCLA4;WAGN4;WARA0;WBEE7;WEND7;WILU7;WLAL7;WMGA7;XMIS4;YAR27;YAR37;YARR7;YEEL7;YELO4;YNKI0;YULA4;BDST4;TOOG4;BEE24;CBLT4;CLEV4;DALB4;GATT4;ROBI4;WARW4;WWLG0;TURO0;TBOB0;PTKL0;PRCE0;NSTA0;NBRK0;KIRR0;IHOE0;HERN0;GNGN0;GLB20;ECOR0;CNBN0;BKNL0;BING0;BARR0;ARD20
    - name: AUSCORS
      valueFrom:
        secretKeyRef:
          name: rtk-status-page-secret
          key: AUSCORS
    args:
      - sed -i 's/AUSCORS/'$(AUSCORS)'/' single.conf &&
        export STATIONS="$(STATIONS)" &&
        for station in $$(echo ${STATIONS} | tr ';' ' '); do echo ${station} &&
            cp single.conf ${station}.conf &&
            sed -i 's/STATION/'${station}'/' ${station}.conf &&
            screen -dm -S ${station} ./rtkrcv -s -o ${station}.conf; done &&
        ./rtkrcv

